/* Generated by tools/build-manifest.mjs — do not edit by hand.
 * 14 images from samples/
 */
window.IMAGEPLAYER_PHOTOS = [
  "samples/01-landscape-3x2.svg",
  "samples/02-portrait-2x3.svg",
  "samples/03-square.svg",
  "samples/04-wide-16x9.svg",
  "samples/05-tall-9x16.svg",
  "samples/06-landscape-4x3.svg",
  "samples/07-portrait-3x4.svg",
  "samples/08-panorama.svg",
  "samples/09-tall-panorama.svg",
  "samples/10-landscape-5x4.svg",
  "samples/11-portrait-4x5.svg",
  "samples/12-small-landscape.svg",
  "samples/13-odd-ratio.svg",
  "samples/14-large-portrait.svg"
];
