/* Generated by tools/build-manifest.mjs — do not edit by hand.
 * 7 images from photos/
 */
window.IMAGEPLAYER_PHOTOS = [
  "photos/WhatsApp%20Image%202026-07-11%20at%201.17.13%20PM%20(1).jpeg",
  "photos/WhatsApp%20Image%202026-07-11%20at%201.17.13%20PM.jpeg",
  "photos/WhatsApp%20Image%202026-07-11%20at%201.18.54%20PM.jpeg",
  "photos/WhatsApp%20Image%202026-07-11%20at%201.19.57%20PM.jpeg",
  "photos/WhatsApp%20Image%202026-07-11%20at%201.20.17%20PM.jpeg",
  "photos/WhatsApp%20Image%202026-07-11%20at%201.21.40%20PM.jpeg",
  "photos/WhatsApp%20Image%202026-07-11%20at%201.23.16%20PM.jpeg"
];
